language: node_js

node_js:
- '8'

cache:
  directories:
  - "$HOME/.npm"
  - node_modules

stages:
  - tests

jobs:
  include:
    - stage: tests
      name: Vouching tests
      install: npm install
      script: npm test
